### ISSUE TITLE
vscode-languageserver-types prints (benign) errors during build

### ISSUE THREAD

**Issue by bert88sta** [extr0py/oni#397]
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-linux@^1.0.3 (node_modules/7zip-bin/node_modules/7zip-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-linux@1.0.3: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@^2.0.2 (node_modules/7zip-bin/node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.0.2: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})


 Bret@Brets-MBP  ~/oni   master  npm run build

> oni@0.2.2 build /Users/Bret/oni
> npm run build:browser && npm run build:plugins


> oni@0.2.2 build:browser /Users/Bret/oni
> webpack --config browser/webpack.production.config.js

ts-loader: Using typescript@2.2.1 and /Users/Bret/oni/browser/tsconfig.src.json
Hash: 8e39bed7107a78a5608a
Version: webpack 1.13.2
Time: 6462ms
    Asset     Size  Chunks             Chunk Names
bundle.js  1.91 MB       0  [emitted]  main
   [0] multi main 28 bytes {0} [built]
    + 348 hidden modules

WARNING in ./~/vscode-languageserver-types/lib/main.js
Critical dependencies:
3:24-31 require function is used in a way in which dependencies cannot be statically extracted
 @ ./~/vscode-languageserver-types/lib/main.js 3:24-31

WARNING in ./~/vscode-languageserver-types/lib/main.d.ts
Module parse failed: /Users/Bret/oni/node_modules/vscode-languageserver-types/lib/main.d.ts Unexpected token (4:7)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (4:7)
    at Parser.pp$4.raise (/Users/Bret/oni/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/Bret/oni/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.expect (/Users/Bret/oni/node_modules/webpack/node_modules/acorn/dist/acorn.js:597:28)
    at Parser.pp$1.parseExportSpecifiers (/Users/Bret/oni/node_modules/webpack/node_modules/acorn/dist/acorn.js:1215:10)
    at Parser.pp$1.parseExport (/Users/Bret/oni/node_modules/webpack/node_modules/acorn/dist/acorn.js:1186:30)
    at Parser.pp$1.parseStatement (/Users/Bret/oni/node_modules/webpack/node_modules/acorn/dist/acorn.js:719:71)
    at Parser.pp$1.parseTopLevel (/Users/Bret/oni/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Users/Bret/oni/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Users/Bret/oni/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/Bret/oni/node_modules/webpack/lib/Parser.js:902:15)
    at NormalModule.<anonymous> (/Users/Bret/oni/node_modules/webpack/lib/NormalModule.js:104:16)
    at NormalModule.onModuleBuild (/Users/Bret/oni/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/Bret/oni/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/Bret/oni/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/Bret/oni/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/Bret/oni/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:415:3)
 @ ./~/vscode-languageserver-types/lib ^\.\/.*$

> oni@0.2.2 build:plugins /Users/Bret/oni
> cd vim/core/oni-plugin-typescript && npm run build


> oni-plugin-typescript@0.0.1 build /Users/Bret/oni/vim/core/oni-plugin-typescript
> npm install && tsc

npm WARN oni-plugin-typescript@0.0.1 No description
npm WARN oni-plugin-typescript@0.0.1 No repository field.
npm WARN oni-plugin-typescript@0.0.1 No license field.
```

**Comment by ohle** [comment]
Same here (Ubuntu 14.04)

**Comment by keforbes** [comment]
I've seen that error too but it doesn't actually affect the resulting build.  Seems benign.  It was introduced by #351 for the language server support.

**Comment by extr0py** [comment]
Ya, unfortunately it looks like `vscode-languageserver-types` has this error when we include via webpack, due to the way it is compiled. It doesn't impact the runtime behavior, so it's safe to ignore - would be nice if there was  a way to filter this out or if that module was made more webpack-friendly.

**Comment by extr0py** [comment]
I'll close this out, since it doesn't affect the resulting build.
