### ISSUE TITLE
0.2.6: C# LSP not working

### ISSUE THREAD

**Issue by extr0py** [extr0py/oni#509]
Looks like the `omnisharp-node-client` is crashing on startup with: `    if (vscode_jsonrpc_1.ConnectionStrategy.is(arg1)) {`

Full trace:
```
C:\oni\node_modules\vscode-languageserver\lib\main.js:471
    if (vscode_jsonrpc_1.ConnectionStrategy.is(arg1)) {
                                           ^

TypeError: Cannot read property 'is' of undefined
    at Object.createConnection (C:\oni\node_modules\vscode-languageserver\lib\main.js:471:44)
    at Object.<anonymous> (C:\oni\node_modules\omnisharp-client\languageserver\server.js:54:42)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
```

Potentially related to package / version changes for `vscode_jsonrpc`? Need to see why it is failing now.

**Comment by extr0py** [comment]
Fixed by #510
